---
- hosts:  control
  become: true
  roles:
   - control
...



# creating roles >>>>>> ansible/roles/control/tasks/main.yml
--
# tasks file for control
  - name: install tools
    apt: name={{item}} state=present update_cache=yes
    with_items:
     - curl
     - nginx
...
